name: Build-Push Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Docker Login
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: cd IntelligenceBattle.Services.GameManager && docker build . --tag ${{secrets.DOCKER_USER}}/intelligence-battle-service:dev
      
    - name: Docker Push
      run: cd IntelligenceBattle.Services.GameManager && docker push ${{secrets.DOCKER_USER}}/intelligence-battle-service:dev
